#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Sep 08 11:54:15 EDT 2021
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim uart_top_tb_behav -key {Behavioral:sim_1:Functional:uart_top_tb} -tclbatch uart_top_tb.tcl -protoinst "protoinst_files/bd_a4e3.protoinst" -protoinst "protoinst_files/smartconect_ip.protoinst" -protoinst "protoinst_files/axi_interconnect_ip.protoinst" -protoinst "protoinst_files/iic_bd.protoinst" -protoinst "protoinst_files/uart_bd.protoinst" -view /home/adg/GitHub/verilog_test/project_1/tb_top_behav.wcfg -view /home/adg/GitHub/verilog_test/project_1/adc_ddr_tb_behav.wcfg -view /home/adg/GitHub/verilog_test/project_1/tb2_top_behav.wcfg -log simulate.log"
xsim uart_top_tb_behav -key {Behavioral:sim_1:Functional:uart_top_tb} -tclbatch uart_top_tb.tcl -protoinst "protoinst_files/bd_a4e3.protoinst" -protoinst "protoinst_files/smartconect_ip.protoinst" -protoinst "protoinst_files/axi_interconnect_ip.protoinst" -protoinst "protoinst_files/iic_bd.protoinst" -protoinst "protoinst_files/uart_bd.protoinst" -view /home/adg/GitHub/verilog_test/project_1/tb_top_behav.wcfg -view /home/adg/GitHub/verilog_test/project_1/adc_ddr_tb_behav.wcfg -view /home/adg/GitHub/verilog_test/project_1/tb2_top_behav.wcfg -log simulate.log

