#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Sep 06 21:21:31 EDT 2021
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto a139cef4d4dc41798a068fb8c24e954b --incr --debug typical --relax --mt 8 -L xil_defaultlib -L lib_pkg_v1_0_2 -L lib_cdc_v1_0_2 -L axi_lite_ipif_v3_0_4 -L interrupt_control_v3_1_4 -L axi_iic_v2_1_0 -L dist_mem_gen_v8_0_13 -L blk_mem_gen_v8_4_4 -L lib_bmg_v1_0_13 -L axi_traffic_gen_v3_0_10 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot axi_iic_0_exdes_tb_behav xil_defaultlib.axi_iic_0_exdes_tb xil_defaultlib.glbl -log elaborate.log"
xelab -wto a139cef4d4dc41798a068fb8c24e954b --incr --debug typical --relax --mt 8 -L xil_defaultlib -L lib_pkg_v1_0_2 -L lib_cdc_v1_0_2 -L axi_lite_ipif_v3_0_4 -L interrupt_control_v3_1_4 -L axi_iic_v2_1_0 -L dist_mem_gen_v8_0_13 -L blk_mem_gen_v8_4_4 -L lib_bmg_v1_0_13 -L axi_traffic_gen_v3_0_10 -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot axi_iic_0_exdes_tb_behav xil_defaultlib.axi_iic_0_exdes_tb xil_defaultlib.glbl -log elaborate.log

